# Generated by Django 6.1.1 on 2026-09-13 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eligivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do servidor')),
                ('grupo_impedimento', models.CharField(blank=True, help_text='Preenchido automaticamente quando este elegível também consta na base de votantes, com o respectivo setor. Usado para aplicar a regra de impedimento na hora da votação.', max_length=255, null=True, verbose_name='Setor / grupo de impedimento')),
            ],
            options={
                'verbose_name': 'Elegível (pode receber voto)',
                'verbose_name_plural': 'Elegíveis (podem receber voto)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do servidor')),
                ('grupo_impedimento', models.CharField(max_length=255, verbose_name='Setor (grupo de impedimento)')),
                ('ja_votou', models.BooleanField(default=False, verbose_name='Já votou')),
                ('identificado_em', models.DateTimeField(blank=True, null=True, verbose_name='Identificado em')),
            ],
            options={
                'verbose_name': 'Votante',
                'verbose_name_plural': 'Votantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora do voto')),
                ('eligivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos_recebidos', to='votos.eligivel', verbose_name='Voto para')),
                ('votante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voto', to='votos.votante', verbose_name='Votante')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
